version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    expose:
      - "3000"

  proxy:
    build:
      context: ./proxy
    container_name: proxy
    ports:
      - "8080:80"
    depends_on:
      - backend
